### ISSUE TITLE
Classpath error during runtime  - NoClassDefFoundError

### ISSUE THREAD

**Issue by SomMeri** [bonprix/vaadin-combobox-multiselect#45]
Multiselect combobox is missing some needed dependencies by default. An attempt to add and use it in simple vaadin application results in runtime error.

Relevant piece of runtime error stack trace (full stack trace is on the bottom):
````
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.vaadin.addons.comboboxmultiselect.ComboBoxMultiselect.paintContent(ComboBoxMultiselect.java:491)
	at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65)
````

### Workaround
Add following into pom.xml:
````
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-lang3</artifactId>
	<version>3.0</version>
</dependency>
````

### Steps to reproduce:
1) Create new project using vaadin 7.7.8 archetype: 
  `mvn -B archetype:generate -DarchetypeGroupId=com.vaadin -DarchetypeArtifactId=vaadin-archetype-application -DarchetypeVersion=7.7.8 -DgroupId=org.test -DartifactId=vaadin-app -Dversion=1.0-SNAPSHOT`

1) Build and run the app: `mvn clean package jetty:run`

1) Default application at `http://localhost:8080/' works correctly

1) Add vaadin-combobox-multiselect dependency 
````xml
<dependency>
	<groupId>org.vaadin.addons</groupId>
	<artifactId>vaadin-combobox-multiselect</artifactId>
	<version>1.2.2</version>
</dependency>
````

5) Build and run the app: `mvn clean package jetty:run` - build is successful and app still runs ok.

1) Change `init` method in generated `MyUI` class and add [`NamedObject`](https://github.com/bonprix/vaadin-combobox-multiselect/blob/7d46fe60cc5257f84a717010b2b7545868a67c6d/vaadin-combobox-multiselect-demo/src/main/java/org/vaadin/addons/demo/model/NamedObject.java) class
````java
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
     // Initialize a list with items
        List<NamedObject> list = new ArrayList<NamedObject>();
        NamedObject vaadin = new NamedObject(2L, "Vaadin");
        list.add(new NamedObject(1L, "Java"));
        list.add(vaadin);
        list.add(new NamedObject(3L, "Bonprix"));
        list.add(new NamedObject(4L, "Addon"));

        // Initialize the ComboBoxMultiselect
        final ComboBoxMultiselect comboBoxMultiselect = new ComboBoxMultiselect();
        comboBoxMultiselect.setInputPrompt("Type here");
        comboBoxMultiselect.setCaption("ComboBoxMultiselect");
        comboBoxMultiselect.addItems(list);
        comboBoxMultiselect.select(vaadin);
        
        layout.addComponents(comboBoxMultiselect);
        layout.setMargin(true);
        layout.setSpacing(true);
        
        setContent(layout);
    }
````

8) Build and run the app: `mvn clean package jetty:run`

1) App does not load and returns an error:
````
HTTP ERROR 500
Problem accessing /. Reason:
    Server Error

javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:382)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	
       [... a lot more]
```````

### Full error:
````
HTTP ERROR 500
Problem accessing /. Reason:
    Server Error

javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:382)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.vaadin.server.ServiceException: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1474)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1434)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	... 29 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.vaadin.addons.comboboxmultiselect.ComboBoxMultiselect.paintContent(ComboBoxMultiselect.java:491)
	at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65)
	at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:143)
	at com.vaadin.server.communication.UIInitHandler.getInitialUidl(UIInitHandler.java:291)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:80)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	... 38 more
````

**Comment by thorbenvh8** [comment]
we will look into it! :)

**Comment by thorbenvh8** [comment]
sorry couldnt reproduce this problem, check version 2.1
