### ISSUE TITLE
Selection does not work

### ISSUE THREAD

**Issue by thomaspp** [bonprix/vaadin-combobox-multiselect#68]
Hello!

I receive always the following error:

```
java.lang.NoSuchFieldException: selection
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.vaadin.addons.ComboBoxMultiselect.updateSelection(ComboBoxMultiselect.java:866)
	at org.vaadin.addons.ComboBoxMultiselect.updateSelection(ComboBoxMultiselect.java:848)
	at org.vaadin.addons.ComboBoxMultiselect$1.updateSelection(ComboBoxMultiselect.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)java.lang.NoSuchFieldException: selection
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.vaadin.addons.ComboBoxMultiselect.updateSelection(ComboBoxMultiselect.java:866)
	at org.vaadin.addons.ComboBoxMultiselect.updateSelection(ComboBoxMultiselect.java:848)
	at org.vaadin.addons.ComboBoxMultiselect.updateSelection(ComboBoxMultiselect.java:825)
	at com.vaadin.ui.AbstractMultiSelect.updateSelection(AbstractMultiSelect.java:306)
	at com.vaadin.ui.AbstractMultiSelect.setValue(AbstractMultiSelect.java:216)
	at
```
The combobox is filled with my data, but the selection by clicking on the values and also the selecting via my software causes this issue. Does anyone have an idea?

One further question: Is there a possiblity to order the entries in the combobox like I added the items to it?

Thanks in advance!

Best Regards,
Thomas

**Comment by beerni** [comment]
Same error. Any update on this?

**Comment by markusweisssiemens** [comment]
Maybe a little bit too late but the problem is appearing once you extend the ComboBoxMultiselect component because in the code there's a reflection call:

```java
final Field f1 = getSelectionBaseClass().getDeclaredField("selection");
...
protected Class<?> getSelectionBaseClass() {
        return this.getClass()
                .getSuperclass();
    }
```

and this is failing if you extended the component once more.

You can get around this problem e.g. if you replace the code by:

```java
final Field f1 = getFieldRecursive(this.getClass(), "selection");
...
protected Field getFieldRecursive(Class clazz, String name) {
        if(clazz == null) {
            return null;
        }
        try {
            return clazz.getDeclaredField(name);
        } catch(NoSuchFieldException | SecurityException | IllegalArgumentException e) {
            return getFieldRecursive(clazz.getSuperclass(), name);
        }
    }
```

Maybe you can add this fix to the next version

**Comment by scho** [comment]
Another way to fix it, is to simply put the following into your class extending `ComboBoxMultiselect`:

```java
	@Override
	protected Class<?> getSelectionBaseClass() {
		return AbstractMultiSelect.class;
	}
```
